[pytest]
markers =
    patient_sum_treatment_cost_per_facility_type: mark for patient sum treatment cost per facility type tests
    parquet_data: mark for parquet data tests
    facility_name_min_time_spent_per_visit_date: mark for facility name min time spent per visit date tests
    smoke: mark for smoke tests
    facility_type_avg_time_spent_per_visit_date
# python_files
python_files = test_*.py
